### ISSUE TITLE
RuntimeError: Incorrect 3D attn_mask shape in nn_model.py during audio path testing

### ISSUE THREAD

**Issue by Masoudvahid** [bala1144/Imitator#19]
I encountered a runtime error while running the test script test_model_external_audio.py. The error occurs during the execution of test_model_external_audio.py. It appears to be related to the shape of the 3D attention mask used in the nn_model.py file.
The script works fine with only some specific wav audio files and failes on others.

**Error Traceback:**
`Traceback (most recent call last):
  File "/opt/pycharm/LipSync/Imitator/imitator/test/test_model_external_audio.py", line 191, in <module>
    tester.run_test_on_the_audio_path(opt, opt.model, best_ckpt)
  File "/opt/pycharm/LipSync/Imitator/imitator/test/test_model_external_audio.py", line 124, in run_test_on_the_audio_path
    out_results = self.run_on_wav_file(template,
  File "/opt/pycharm/LipSync/Imitator/imitator/test/test_model_external_audio.py", line 94, in run_on_wav_file
    prediction = model.nn_model.predict(sampled_processed_audio, template, one_hot)
  File "/opt/pycharm/LipSync/Imitator/imitator/models/nn_model.py", line 329, in predict
    gen_viseme_feat = self.transformer_decoder(vertice_input, hidden_states, tgt_mask=tgt_mask, memory_mask=memory_mask)
  File "/opt/miniconda3/envs/imitator/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/miniconda3/envs/imitator/lib/python3.8/site-packages/torch/nn/modules/transformer.py", line 248, in forward
    output = mod(output, memory, tgt_mask=tgt_mask,
  File "/opt/miniconda3/envs/imitator/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/miniconda3/envs/imitator/lib/python3.8/site-packages/torch/nn/modules/transformer.py", line 451, in forward
    x = self.norm1(x + self._sa_block(x, tgt_mask, tgt_key_padding_mask))
  File "/opt/miniconda3/envs/imitator/lib/python3.8/site-packages/torch/nn/modules/transformer.py", line 460, in _sa_block
    x = self.self_attn(x, x, x,
  File "/opt/miniconda3/envs/imitator/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/miniconda3/envs/imitator/lib/python3.8/site-packages/torch/nn/modules/activation.py", line 1003, in forward
    attn_output, attn_output_weights = F.multi_head_attention_forward(
  File "/opt/miniconda3/envs/imitator/lib/python3.8/site-packages/torch/nn/functional.py", line 5016, in multi_head_attention_forward
    raise RuntimeError(f"The shape of the 3D attn_mask is {attn_mask.shape}, but should be {correct_3d_size}.")
RuntimeError: The shape of the 3D attn_mask is torch.Size([4, 600, 600]), but should be (4, 601, 601).
`

steps to produce:
`python test_model_external_audio.py -m pretrained_model/generalized_model_mbp_vel --audio assets/demo/test.wav -t FaceTalk_170731_00024_TA -c 5`

**Comment by bala1144** [comment]
I think this issue is related to different versions of the torch, please install the correct version of torch from the env file and try again
